name: LaTeX and pray

on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/texlive-action@v2
        with:
          docker_image: ghcr.io/xu-cheng/texlive-full:20230801
          run: |
            apk add pdflatex
            cd docs
            pdflatex -interaction=nonstopmode -halt-on-error stitch-documentation.tex
            

# praying
